### 1. Create Tour (POST)
POST http://localhost:3000/api/tours/create-tour
Content-Type: application/json

{
  "type": "Hiking",
  "destination": "Mount Kilimanjaro",
  "duration": "7 days",
  "price": "5000"
}

### 2. Update Tour (PUT)
PUT http://localhost:3000/api/tours/E590050B-2345-40DD-822E-71AC8848AABF
Content-Type: application/json

{
  "type": "Sightseeing",
  "duration": "5 days",
  "price": "3000"
}

### 3. Fetch All Tours (GET)
GET http://localhost:3000/api/tours/tours

### 4. Fetch Tour by ID (GET)
GET http://localhost:3000/api/tours/E590050B-2345-40DD-822E-71AC8848AABF

### 5. Delete Tour (DELETE)
DELETE http://localhost:3000/api/tours/ABE9C82A-2D32-4302-8299-BCB43C25CE3D
