### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstname": "Carolyne",
  "lastname": "Martin",
  "email": "carol.martin@example.com",
  "password": "password123"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "carol.doe@example.com",
  "password": "password123"
}

### Update User
PUT http://localhost:3000/api/users/B375BD69-42D0-4644-B583-BB1D6EB20634
Content-Type: application/json

{
  "firstname": "Updated John",
  "lastname": "Updated Doe"
}

### Delete User
DELETE http://localhost:3000/api/users/B375BD69-42D0-4644-B583-BB1D6EB20634

### Get All Users
GET http://localhost:3000/api/users

### Get User by ID
GET http://localhost:3000/api/users/B375BD69-42D0-4644-B583-BB1D6EB20634
